#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/matt/PycharmProjects/Stylized-Cell-Inference/venv/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/matt/PycharmProjects/Stylized-Cell-Inference/venv/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/matt/PycharmProjects/detailed-single-cell/sim_details/components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
